site_name: IOTstack
site_description: 'Docker stack for getting started on IOT on the Raspberry PI'
theme:
  name: material
  features:
    - tabs
  plugins:
    - search
    - awsome-pages
    - git-authors
    - admonition
    - git-revision-date-localized
