  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    x-network_mode: host  # see IOTstack documentation
    ports:
      - "53:53/tcp"       # regular DNS
      - "53:53/udp"       # regular DNS
      - "3001:3000/tcp"   # only active until port 8089 becomes active
      - "8089:8089/tcp"   # regular administrative interface
    # - "443:443/tcp"     # HTTPS/DNS-over-HTTPS
    # - "784:784/udp"     # DNS-over-QUIC
    # - "853:853/tcp"     # DNS-over-TLS
    # - "5443:5443/tcp"   # DNSCrypt
    # - "5443:5443/udp"   # DNSCrypt
    # - "6060:6060/tcp"   # debugging profiles
    # - "67:67/udp"       # DHCP service (host mode)
    # - "68:68/tcp"       # DHCP service (host mode)
    # - "68:68/udp"       # DHCP service (host mode)
    volumes:
      - ./volumes/adguardhome/workdir:/opt/adguardhome/work
      - ./volumes/adguardhome/confdir:/opt/adguardhome/conf
