  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    env_file:
      - ./services/heimdall/heimdall.env
    volumes:
      - ./volumes/heimdall/config:/config
    ports:
      - 8882:80
      - 8883:443
    restart: unless-stopped
