portainer-ce:
  container_name: portainer-ce
  image: portainer/portainer-ce
  restart: unless-stopped
  ports:
    - "8000:8000"
    - "9000:9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data
  environment:
    - VIRTUAL_HOST=~^portainer\..*\.xip\.io
    - VIRTUAL_PORT=9000
