motioneye:
  container_name: motioneye
  image: dontobi/motioneye.rpi:latest
  restart: unless-stopped
  x-network_mode: host
  ports:
  - 8765:8765
  - 8766:8082
  environment:
  - TZ=Etc/UTC
  volumes:
  - ./volumes/motioneye/etc_motioneye:/etc/motioneye
  - ./volumes/motioneye/var_lib_motioneye:/var/lib/motioneye
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
