<<<<<<< HEAD
tasmoadmin:
  container_name: tasmoadmin
  image: ghcr.io/tasmoadmin/tasmoadmin:latest
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
  ports:
    - "8088:80"
  volumes:
    - ./volumes/tasmoadmin/data:/data

=======
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./volumes/tasmoadmin/data:/data
    environment:
      - VIRTUAL_HOST=~^tasmoadmin\..*\.xip\.io
      - VIRTUAL_PORT=8088
      
>>>>>>> other-IOTstack/feature/AddNginxProxy
