  mopidy:
    #Build image from Dockerfile
    build: ./services/mopidy/.
    #Uncomment below line to use pre-built image
    #image: hum8lefool/mopidy
    container_name: mopidy
    user: 1000:1000
    # Run as root in case of issues
    ports:
      - "6600:6600"
      - "6680:6680"
      - "5555:5555/udp"
    volumes:
      - ./services/mopidy/mopidy.conf:/config/mopidy.conf
      - ./volumes/mopidy/local:/var/lib/mopidy/local
      - ./volumes/mopidy/media:/var/lib/mopidy/media:ro
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
