  mopidy:
    image: wernight/mopidy
    container_name: mopidy
    user: 1000:1000
    # Run as root in case of issues
    ports:
      - "6600:6600"
      - "6680:6680"
      - "5555:5555/udp"
    volumes:
      - ./volumes/mopidy/local:/var/lib/mopidy/local
      - ./volumes/mopidy/mopidy.conf:/config/mopidy.conf
      - ./volumes/mopidy/media:/var/lib/mopidy/media:ro
    devices:
    # RPi 4 Sound Device
    - /dev/snd:/dev/snd
    restart: unless-stopped
